name: doodle_fun_play
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+6

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+1
  image: ^4.1.7
  image_picker: ^1.0.8
  matrix_gesture_detector_pro: ^1.0.0
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.7.0
  in_app_review: ^2.0.9
  ad_gridview: ^0.0.4
  share_plus: ^8.0.2
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  google_mobile_ads: ^5.0.0
  url_launcher: ^6.2.6
#  image_gallery_saver: ^2.0.3
#  flutter_image_processing: ^0.0.4
#  edge_detection: ^1.1.3
  upgrader: ^10.2.0
  cupertino_icons: ^1.0.8
#  change_app_package_name: ^1.1.0

flutter_native_splash:
  android: true
  ios: true
  web: true
  color: "#EAF8FE"
  image: 'assets/splash_screen.png'
  android_12:
    image: "assets/android_12_splash.png"
    color: "#EAF8FE"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
  android: "ic_launcher"
  image_path: "assets/splash_image.png"



  flutter_lints: ^2.0.3

# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/alphabet/
    - assets/tree/
    - assets/sports/
    - assets/fun/
    - assets/hill/
    - assets/digit/
    - assets/car/
    - assets/flying/
    - assets/animal/
    - assets/listPhoto/
    - assets/anime/
    - assets/

  fonts:
    - family: orbitron
      fonts:
        - asset: assets/orbitron.ttf
